######################################################################
##
## Filename: arwen_s_prog_tb.udo
## Created on: Tue May 17 12:46:05 ora legale Europa occidentale 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
