######################################################################
##
## Filename: gp_if_tb.udo
## Created on: Wed Mar 30 13:21:42 ora legale Europa occidentale 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
