######################################################################
##
## Filename: tcs_tx_MEP_tb.udo
## Created on: Thu Feb 02 17:02:26 ora solare Europa occidentale 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
