######################################################################
##
## Filename: wb_to_ram_tb.udo
## Created on: Wed Jun 08 11:19:02 ora legale Europa occidentale 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
