   
################################################################################
##$Date: 2009/11/26 05:47:37 $
##$Revision: 1.1 $
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /
## \   \   \/     Vendor : Xilinx
##  \   \         Version : 2.1
##  /   /         Application : RocketIO GTP Transceiver Wizard
## /___/   /\     Filename : simulate_mti.do
## \   \  /  \
##  \___\/\___\
##
##
## Script SIMULATE_MTI.DO
## Generated by Xilinx RocketIO GTP Transceiver Wizard
## 
## 
## (c) Copyright 2006-2010 Xilinx, Inc. All rights reserved.
## 
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
## 
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
## 
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES. 


##***************************** Beginning of Script ***************************
        
## If MTI_LIBS is defined, map unisim and simprim directories using MTI_LIBS
## This mode of mapping the unisims libraries is provided for backward 
## compatibility with previous wizard releases. If you don't set MTI_LIBS
## the unisim libraries will be loaded from the paths set up by compxlib in
## your modelsim.ini file

set XILINX   $env(XILINX)
if [info exists env(MTI_LIBS)] {    
    set MTI_LIBS $env(MTI_LIBS)
    vlib UNISIM
    vmap UNISIM $MTI_LIBS/unisim
   
    vlib SECUREIP
    vmap SECUREIP $MTI_LIBS/secureip
}

## Create and map work directory
vlib work
vmap work work

##MGT Wrapper
vcom -93 -work work  ../../../single_channel_aurora_xc5vsx95t_tile.vhd;
vcom -93 -work work  ../../../single_channel_aurora_xc5vsx95t.vhd;


vcom -93 -work work  ../../example_design/mgt_usrclk_source_pll.vhd;


##Example Design modules
vcom -93 -work work  ../../example_design/frame_gen.vhd;
vcom -93 -work work  ../../example_design/frame_check.vhd;
vcom -93 -work work  ../../example_design/single_channel_aurora_xc5vsx95t_top.vhd;
vcom -93 -work work  ../demo_tb.vhd;

##Other modules
vcom -93 -work work ../sim_reset_mgt_model.vhd;

##Load Design
vsim -t 1ps work.DEMO_TB -voptargs="+acc"

##Load signals in wave window
view wave
do wave_mti.do

##Run simulation
run 25 us


